/**
 * In-tree browser build (no bundler) — REQ-BUILD-003 / standalone mandate.
 *
 * WHAT: emits the web client + its browser-safe workspace dependencies to native ES modules and
 * writes a self-contained `dist/esm/index.html` whose <script type="importmap"> resolves the bare
 * `@bsv-poker/*` specifiers to the emitted files. The browser's own module loader is the runtime.
 *
 * HOW: (1) run `tsc -p tsconfig.build.json` — pure type-strip, `./x.ts`→`./x.js` rewrite, bare
 * workspace specifiers left intact; (2) read every browser-safe package's `exports` map and project
 * each entry to its emitted `.js` path under dist/esm; (3) emit index.html with that import map.
 *
 * WHY (no bundler): this is reference infrastructure that must not depend on external build code
 * (Vite/Rollup/esbuild are large external dependencies an auditor cannot fully see). `tsc` is the
 * type system the project already uses; the import map is a ~30-line, fully-visible artifact. The
 * app's static module graph is browser-safe (no node:crypto package is reachable — see
 * tsconfig.build.json), so no tree-shaking is required for correctness.
 *
 * Run: `node build.ts` (from apps/client-web). Exits non-zero if tsc fails to emit the entry module.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = join(APP_DIR, '..', '..');
const DIST = join(APP_DIR, 'dist', 'esm');

/** Browser-safe workspace packages whose `exports` feed the import map (must match tsconfig.build). */
const BROWSER_PACKAGES = [
  'protocol-types',
  'engine',
  'hand-eval',
  'game-holdem',
  'game-omaha',
  'game-stud',
  'game-draw',
  'game-razz',
  'ui-core',
  'app-services',
] as const;

/** The app's entry module, as emitted (rootDir = repo root → preserved tree under dist/esm). */
const ENTRY = './apps/client-web/src/main.js';

interface PackageJson {
  readonly name: string;
  readonly exports?: Record<string, string> | string;
}

function compile(): void {
  const tsc = join(ROOT, 'node_modules', 'typescript', 'bin', 'tsc');
  console.log('=== tsc emit (tsconfig.build.json) ===');
  const r = spawnSync('node', [tsc, '-p', 'tsconfig.build.json'], { cwd: APP_DIR, stdio: 'inherit', shell: false });
  // noEmitOnError is false, so tsc emits even with diagnostics; a non-zero status here means a hard
  // failure (config/IO). We still verify the entry module exists below regardless.
  if (r.status !== 0) console.warn(`tsc exited ${r.status} (diagnostics above) — verifying emit…`);
}

/** Build the import map: every export subpath of every browser package → its emitted `.js` URL. */
function buildImportMap(): Record<string, string> {
  const imports: Record<string, string> = {};
  for (const pkg of BROWSER_PACKAGES) {
    const pkgDir = join(ROOT, 'packages', pkg);
    const meta = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')) as PackageJson;
    const exp = meta.exports;
    const entries: [string, string][] =
      typeof exp === 'string' ? [['.', exp]] : exp ? Object.entries(exp) : [['.', './src/index.ts']];
    for (const [key, value] of entries) {
      if (key === './*' || value.includes('*')) continue; // no wildcard exports in this repo
      const specifier = key === '.' ? meta.name : `${meta.name}${key.slice(1)}`;
      const rel = value.replace(/^\.\//, '').replace(/\.ts$/, '.js');
      imports[specifier] = `./packages/${pkg}/${rel}`;
    }
  }
  return imports;
}

function writeHtml(importMap: Record<string, string>): void {
  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BSV Poker — regtest play-money client</title>
    <!-- In-tree import map (generated by build.ts). Resolves bare @bsv-poker/* specifiers to the
         tsc-emitted ES modules. No bundler: the browser module loader is the runtime. -->
    <script type="importmap">
${JSON.stringify({ imports: importMap }, null, 6)}
    </script>
  </head>
  <body style="margin:0;background:#0d0d0d;color:#eee;font-family:system-ui,sans-serif">
    <div id="root"></div>
    <script type="module" src="${ENTRY}"></script>
  </body>
</html>
`;
  writeFileSync(join(DIST, 'index.html'), html, 'utf8');
}

function main(): void {
  compile();
  const entryFile = join(DIST, 'apps', 'client-web', 'src', 'main.js');
  if (!existsSync(entryFile)) {
    console.error(`BUILD FAILED: entry module not emitted at ${entryFile}`);
    if (existsSync(DIST)) console.error('dist/esm contents:', readdirSync(DIST));
    process.exit(1);
  }
  const importMap = buildImportMap();
  writeHtml(importMap);
  console.log(`\nBUILD OK — dist/esm/index.html written with ${Object.keys(importMap).length} import-map entries.`);
}

main();
