using BsvPoker.Crypto;

namespace BsvPoker.Core.Games;

/// <summary>
/// EP4152683B1 end-of-game RECLAMATION COVENANT — the holding-account organ that recovers a committed pot
/// when a party goes unresponsive or malicious MID-GAME, without theft and without stranding funds.
///
/// The threat: the pot is in threshold custody (<see cref="ThresholdCustody"/>) under a FIRST dealerless
/// threshold key a·G shared across all players. Settlement (pay the winner) and the nLockTime refund both
/// require t+1 players to jointly sign. If a player griefs — refuses to sign the agreed payout, or worse,
/// tries to extort by withholding — the honest majority must be able to RECLAIM the committed pot and finish
/// the game, while a sub-threshold/unresponsive party must never be able to steal a satoshi or freeze the money.
///
/// The EP4152683B1 mechanism (transcribed in transcript/20260610-174905, lines 11-13):
///   "a holding account under a 2nd threshold key + time-lock recovery if a party is unresponsive/malicious
///    (iteratively swap the faulty share's party). i.e. reclamation == threshold sign + nLockTime recovery."
///
/// So this organ COMPOSES the proven primitives only — it fabricates no new crypto:
///   1. <see cref="ReclaimToHolding"/>      — t+1 honest players THRESHOLD-sign (with the FIRST custody key) a
///      tx that sweeps the pot into a P2PKH to a SECOND threshold key a'·G (the holding account). On-chain this
///      is an ordinary single-key P2PKH spend → P2PKH send (no fingerprint), verified on the consensus path.
///   2. <see cref="SwapFaultyShare"/>       — the SECOND threshold key is freshly generated by a dealerless
///      JVRSS over only the RESPONSIVE parties (the faulty party's share is swapped out); it is held by nobody.
///   3. <see cref="SettleHolding"/>         — pay ONLY the agreed parties out of the holding account, THRESHOLD-
///      signing with the second key. A sub-threshold coalition cannot move it; payouts can never exceed the pot.
///   4. <see cref="BuildHoldingRecovery"/>  — a pre-agreed nLockTime n-of-n RECOVERY of the holding account
///      (<see cref="Chain.BuildNofNRecovery"/>), co-signed at reclamation, so the money is NEVER stranded even
///      if the responsive parties later deadlock: after the lock height anyone can broadcast the agreed refund.
///
/// Safety (no theft) is structural: every spend out of either account needs a threshold / n-of-n signature
/// over the EXACT outputs (the FORKID sighash binds value and destinations), so no party below threshold and
/// no swapped-out faulty party can redirect funds. Liveness (no stranding) is the time-locked refund. Value is
/// conserved end-to-end (pot − fees), exactly as the custody and n-of-n-pot organs already guarantee.
/// </summary>
public static class ReclamationCovenant
{
    /// <summary>The holding account's locking script: an ordinary P2PKH to the SECOND threshold key a'·G —
    /// identical in shape to the custody pot, so the reclamation leaves no multisig fingerprint on-chain.</summary>
    public static byte[] HoldingLock(ThresholdEcdsa.Shared holdingKey) => Chain.P2pkhLockForPub(holdingKey.PublicKey);

    /// <summary>
    /// SWAP THE FAULTY PARTY'S SHARE. Generate the SECOND threshold key a'·G for the holding account by a fresh
    /// dealerless JVRSS over ONLY the responsive parties (<paramref name="responsiveCount"/> of them). The faulty
    /// party contributes no polynomial and holds no share of a', so it cannot participate in any holding-account
    /// signature — it has been iteratively swapped out, exactly the EP4152683B1 recovery step. The new key is a
    /// completely independent secret (no relationship to the custody key a), held by nobody.
    /// </summary>
    public static ThresholdEcdsa.Shared SwapFaultyShare(int responsiveCount, int degree)
    {
        if (responsiveCount < 2 * degree + 1)
            throw new ArgumentException($"need {2 * degree + 1} responsive parties to re-key at degree {degree} (faulty share swapped out)");
        return ThresholdEcdsa.Jvrss(responsiveCount, degree);
    }

    /// <summary>
    /// RECLAIM the committed pot into the holding account. The t+1 responsive players jointly THRESHOLD-sign
    /// (with the FIRST custody key) a tx that spends the pot UTXO to a single P2PKH output locked to the SECOND
    /// threshold key a'·G. The result verifies on the ordinary consensus path (<see cref="Chain.VerifyP2pkhInput"/>).
    /// No party holds either key; a sub-threshold set cannot produce this signature, so the reclaim cannot be
    /// forged. Value is conserved (pot − fee moves into the holding account).
    /// </summary>
    public static Chain.Tx ReclaimToHolding(string potTxid, uint vout, long amount, long fee,
        ThresholdEcdsa.Shared custodyKey, ThresholdEcdsa.Shared holdingKey)
    {
        if (fee < 0 || fee >= amount) throw new ArgumentException("fee out of range (0 ≤ fee < amount)");
        var outs = new List<Chain.TxOut> { new(amount - fee, HoldingLock(holdingKey)) };
        var ins = new List<Chain.TxIn> { new(potTxid, vout, Array.Empty<byte>(), 0xffffffff) };
        var tx = new Chain.Tx(2, ins, outs, 0);
        var digest = Chain.SighashForkId(tx, 0, ThresholdCustody.PotLock(custodyKey), amount);
        var sig = ThresholdEcdsa.SignDigest(digest, custodyKey);
        return Chain.ApplyP2pkhSig(tx, 0, sig, custodyKey.PublicKey);
    }

    /// <summary>
    /// SETTLE the holding account to the agreed parties (the reclaimed game outcome). Builds one P2PKH output
    /// per payee, THRESHOLD-signs (with the SECOND/holding key) the spend, and assembles the standard scriptSig.
    /// The faulty party — having no share of a' — cannot take part. Payouts can never exceed the holding value
    /// (no money is created); the fee is the holding value minus the paid total. Verifies on the consensus path.
    /// </summary>
    public static Chain.Tx SettleHolding(string holdingTxid, uint vout, long holdingValue,
        IReadOnlyList<(byte[] Pub, long Amount)> payouts, ThresholdEcdsa.Shared holdingKey)
    {
        foreach (var p in payouts) if (p.Amount < 0) throw new ArgumentException("negative payout");
        var outs = payouts.Where(p => p.Amount > 0).Select(p => new Chain.TxOut(p.Amount, Chain.P2pkhLockForPub(p.Pub))).ToList();
        if (outs.Count == 0) throw new ArgumentException("no positive payouts");
        long paid = outs.Sum(o => o.Value);
        if (paid > holdingValue) throw new ArgumentException("payouts exceed the holding account (would create money)");
        var ins = new List<Chain.TxIn> { new(holdingTxid, vout, Array.Empty<byte>(), 0xffffffff) };
        var tx = new Chain.Tx(2, ins, outs, 0);
        var digest = Chain.SighashForkId(tx, 0, HoldingLock(holdingKey), holdingValue);
        var sig = ThresholdEcdsa.SignDigest(digest, holdingKey);
        return Chain.ApplyP2pkhSig(tx, 0, sig, holdingKey.PublicKey);
    }

    /// <summary>
    /// A pre-agreed nLockTime RECOVERY of the holding account, THRESHOLD-signed with the SECOND key: refunds
    /// each agreed party (one output per payee) but is only final after <paramref name="lockHeight"/> (non-final
    /// sequence so the locktime binds). The responsive parties co-sign this AT RECLAMATION, before relying on the
    /// holding account, so even if they later deadlock no satoshi can be stranded — anyone broadcasts it after the
    /// timeout. Refunds can never exceed the holding value. Mirrors <see cref="ThresholdCustody.BuildRecovery"/>.
    /// </summary>
    public static Chain.Tx BuildHoldingRecovery(string holdingTxid, uint vout, long holdingValue,
        IReadOnlyList<(byte[] Pub, long Amount)> refunds, ThresholdEcdsa.Shared holdingKey, uint lockHeight)
    {
        foreach (var rf in refunds) if (rf.Amount < 0) throw new ArgumentException("negative refund");
        var outs = refunds.Where(r => r.Amount > 0).Select(r => new Chain.TxOut(r.Amount, Chain.P2pkhLockForPub(r.Pub))).ToList();
        if (outs.Count == 0) throw new ArgumentException("no positive refunds");
        if (outs.Sum(o => o.Value) > holdingValue) throw new ArgumentException("refunds exceed the holding account (would create money)");
        var ins = new List<Chain.TxIn> { new(holdingTxid, vout, Array.Empty<byte>(), 0xfffffffe) }; // non-final → locktime active
        var tx = new Chain.Tx(2, ins, outs, lockHeight);
        var digest = Chain.SighashForkId(tx, 0, HoldingLock(holdingKey), holdingValue);
        var sig = ThresholdEcdsa.SignDigest(digest, holdingKey);
        return Chain.ApplyP2pkhSig(tx, 0, sig, holdingKey.PublicKey);
    }

    /// <summary>
    /// An ALTERNATIVE, covenant-free liveness backstop usable WHEN the holding account is instead an explicit
    /// n-of-n bare-multisig output (every responsive party an equal cosigner): a pre-agreed nLockTime n-of-n
    /// refund (<see cref="Chain.BuildNofNRecovery"/>) returning each party's share after <paramref name="lockHeight"/>.
    /// This is the structural (no-key-held-by-anyone) twin of <see cref="BuildHoldingRecovery"/> for tables that
    /// prefer explicit n-of-n custody of the reclaimed pot over a second threshold key. Unsigned (each party adds
    /// its <see cref="Chain.SignMultisigN"/> signature at setup, exactly as the n-of-n pot organ does).
    /// </summary>
    public static Chain.Tx BuildNofNHoldingRecovery(string holdingTxid, uint vout,
        IReadOnlyList<(byte[] Pub, long Stake)> parties, long fee, uint lockHeight)
        => Chain.BuildNofNRecovery(holdingTxid, vout, parties, fee, lockHeight);
}
